Issue 2065
hwdtech/redirect pull request #7
Opened 2016-10-19 11:25 UTC by Nastsi

Creating 2 classes: PostJson for deserialization and DbJson for serialization. Also some methods for working with it (but it doesn't finished).

2016-10-19 11:42 UTC, maxmalov requested changes

2016-10-19 11:42 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +            //var tree = System.IO.File.ReadAllText("tree.json");
Remove comments from code

2016-10-19 11:42 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +                foreach (var child in array.Children())
Let's start to get common with Linq ;)

```csharp
var target = array.Children().Select(child => {
  var node = CreateNode(child);
￼  serializer.Populate(child.CreateReader(), node);
  return node;
}).ToList();
```

2016-10-19 11:42 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +            switch (type)
Replace switch with `Dictionary<string, Func<ITreeNode>>`, each dictionary value is a factory function for a corresponding class. So you can just pick needed factory by string, call it and return the result. If there is no such entry - throw an exception

2016-10-19 11:42 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +    class ByLanguage : ITreeNode
separate class definitions from each other with empty lines

2016-10-19 11:44 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Controllers/ValuesController.cs
> +            json.Main(tree);
I suppose controller method should return smth?

2016-10-19 11:46 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +    public class JsonWorking
What is this class for? There aren't any effects/output in Main method

2016-10-19 11:48 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +    class PostJson
I propose to move such json definition and `ITreeNode` implemetors classes into a separate files

2016-10-19 11:49 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +            PostJson content = JsonSerializer.CreateDefault().Deserialize<PostJson>(reader);
Lets be consistent during variable declaration. If you're using `var`, keep using it everywhere.

2016-10-19 11:49 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +
too many blank lines

2016-10-19 11:59 UTC, Nastsi commented on RedirectApplication/RedirectApplication/Controllers/ValuesController.cs
> +            json.Main(tree);
It will be done in another ticket

2016-10-19 12:58 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Controllers/ValuesController.cs
> +            json.Main(tree);
It should be added in another ticket PR then. History should be clean to other current/future developers, adding unrelated/dead code can cause many confusions in the future. Less code you ship to PR - less comments you've get ;)

2016-10-19 13:31 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Controllers/ValuesController.cs
> +
remove empty line

2016-10-19 13:32 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +            var target = new List<ITreeNode>();
why is this initialization needed?

2016-10-19 13:35 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Models/JsonModel.cs
> +namespace RedirectApplication.Models
separate usings with empty line

2016-10-19 13:35 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +                return RulesType[type];
Every time it will return exactly same instances, it defers from previous implementation, where instance was created on every method call.

2016-10-19 13:36 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +        public Dictionary<string, ITreeNode> RulesType = new Dictionary<string, ITreeNode>()
Why is this public property?

2016-10-19 13:37 UTC, Nastsi commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +            var target = new List<ITreeNode>();
We figured out that class "TreeNodeConverter : JsonConverter" can't work without any of this methods. I think this is because of  inheritance

2016-10-19 13:38 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Controllers/ValuesController.cs
> +        {
remove trailing whitespace

2016-10-19 13:40 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +            var target = new List<ITreeNode>();
I'm talking about exactly this line initialization, and at the next line variable is being reassigned

2016-10-20 09:26 UTC, Nastsi commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +                return RulesType[type];
Can you, please, explain with more details what did you mean? We compiled this in our draft-project and it worked. Maybe we can't understand something

2016-10-20 11:53 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +                return RulesType[type];
Previous variant:

``` csharp
public ITreeNode CreateNode(JToken obj) 
{
  switch(type) {
    case "foo":
      return new Bar();
    // lots of other cases
  }
}
```

As you can see in the code above on every `CreateNode` new instance of `ITreeNode` implementor will be created.

In the current implementation you've already created instances once in the dictionary initialization and will return these created instances. So it makes `CreateNode` return the same previously created instance instead of creating a new one, as it was in the previous version.

Assume the following code case:

``` csharp

var node = treeNodeConverter.CreateNode({ name: "Composite" });
node.Name = "What a stupid name";

// somewhere else in the code base
var anotherNode = treeNodeConverter.CreateNode({ name: "Composite" });
anotherNode.Name // = ?
```

what value will be stored in `anotherNode.Name`?

2016-10-20 12:55 UTC, maxmalov commented on RedirectApplication/RedirectApplication/Json/Json.cs
> +            var target = array.Children().Select(child => {
aaaaand final polishing: inline unneeded variable and return expression result

2016-10-20 14:38 UTC, maxmalov commented
LGTM, @jacob-l I've no write access here, so merge is up to you

2016-10-20 14:41 UTC, maxmalov commented
One more thing: http://chris.beams.io/posts/git-commit/

`Remarks correction` is an anti-pattern for commit message, instead you should specify why the changes were made

2016-10-21 04:23 UTC, merged